services:
  frontend:
    image: oven/bun:latest
    ports:
      - "5173:5173"  # Format is "HOST:CONTAINER"
    volumes:
      - ./frontend:/app  # Mount the frontend directory to /app in the container
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: bash -c "bun install && bun run dev"
