version: '3'
services:
  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "5173:5173"  # Format is "HOST:CONTAINER"
  #  environment:
  #    - NODE_ENV=development
  java-app:
    build: ./java-prolog-api
    ports:
      - "8080:8080"
    environment:
      - PROLOG_HOST=prolog
      - PROLOG_PORT=4000

  ngrok:
    image: wernight/ngrok
    volumes:
      - ./ngrok.yml:/ngrok.yml  # Mount the ngrok.yml configuration file
    command: ngrok start --config /ngrok.yml --all  # Use the ngrok.yml config
    ports:
      - "4040:4040"  # Expose the ngrok dashboard